/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-104626-gb159975e80-20211120"
#endif /* AVUTIL_FFVERSION_H */
